import { database } from "@/db/raw";
import { products,groupKey } from "@/lib/products";
const cookieName="wishlist_guest";
const headers={"Cache-Control":"no-store"};
const json=(value:unknown,status=200)=>Response.json(value,{status,headers});
async function hash(value:string){return Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)))).map(v=>v.toString(16).padStart(2,"0")).join("");}
function guest(request:Request){const value=request.headers.get("cookie")?.split(";").map(v=>v.trim()).find(v=>v.startsWith(cookieName+"="))?.slice(cookieName.length+1);return value&&/^[a-f0-9]{64}$/.test(value)?value:null;}
function secret(){return Array.from(crypto.getRandomValues(new Uint8Array(32))).map(v=>v.toString(16).padStart(2,"0")).join("");}
function validOrigin(request:Request){return request.headers.get("origin")===new URL(request.url).origin;}
export async function GET(request:Request){try{const token=guest(request)||secret();const owner=await hash(token);const result=await database().prepare("SELECT group_key,item_id,owner_hash FROM reservations").all<{group_key:string;item_id:string;owner_hash:string}>();const response=json({reservations:result.results.map(row=>({groupKey:row.group_key,itemId:row.item_id,mine:row.owner_hash===owner}))});if(!guest(request))response.headers.set("Set-Cookie",`${cookieName}=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=31536000${new URL(request.url).protocol==="https:"?"; Secure":""}`);return response;}catch(error){console.error("reservation load",error);return json({error:"Не вдалося завантажити бронювання. Спробуйте ще раз."},503);}}
export async function POST(request:Request){if(!validOrigin(request))return json({error:"Неприпустимий запит."},403);try{const token=guest(request);if(!token)return json({error:"Увімкніть cookies та оновіть сторінку, щоб забронювати подарунок."},401);const body=await request.json() as {itemId?:unknown;cancelToken?:unknown}; if(!body||typeof body!=="object")return json({error:"Неприпустимі дані."},400);const product=products.find(p=>p.id===body.itemId);if(!product)return json({error:"Такого подарунка немає у списку."},400);const cancelToken=secret();const result=await database().prepare("INSERT INTO reservations (group_key,item_id,owner_hash,cancel_hash,created_at) VALUES (?,?,?,?,?) ON CONFLICT(group_key) DO NOTHING").bind(groupKey(product),product.id,await hash(token),await hash(cancelToken),new Date().toISOString()).run();if(!result.meta.changes)return json({error:"Цей подарунок або інший варіант із цієї групи вже забронювали. Оберіть інший."},409);return json({ok:true,itemId:product.id,cancelToken},201);}catch(error){console.error("reservation save",error);return json({error:"Не вдалося підтвердити бронювання. Оновіть список перед повторною спробою."},503);}}
export async function DELETE(request:Request){if(!validOrigin(request))return json({error:"Неприпустимий запит."},403);try{const body=await request.json() as {itemId?:unknown;cancelToken?:unknown}; if(!body||typeof body!=="object")return json({error:"Неприпустимі дані."},400);const product=products.find(p=>p.id===body.itemId);if(!product)return json({error:"Подарунок не знайдено."},400);const owner=guest(request);const recovery=typeof body.cancelToken==="string"&&/^[a-f0-9]{64}$/.test(body.cancelToken)?body.cancelToken:"";if(!owner&&!recovery)return json({error:"Відкрийте сторінку в браузері, де зробили бронювання, або скористайтеся особистим посиланням."},403);const result=await database().prepare("DELETE FROM reservations WHERE group_key=? AND item_id=? AND (owner_hash=? OR cancel_hash=?)").bind(groupKey(product),product.id,owner?await hash(owner):"",recovery?await hash(recovery):"").run();if(!result.meta.changes)return json({error:"Бронювання вже скасоване або належить іншій людині."},403);return json({ok:true});}catch(error){console.error("reservation cancel",error);return json({error:"Не вдалося скасувати бронювання. Спробуйте ще раз."},503);}}

