"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {ArrowUpRight,ArrowDown,Check,LockKeyhole,X,Copy,Gift} from "lucide-react";
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogClose} from "@/components/ui/dialog";
import {products,groupKey,onePerGroup,type Product} from "@/lib/products";
type Reservation={groupKey:string;itemId:string;mine:boolean};
type Modal={product:Product;mode:"book"|"cancel"|"success";cancelToken?:string};
const price=(p:Product)=>p.price===null?"Ціна в магазині":new Intl.NumberFormat("uk-UA").format(p.price)+" ₴";
const sections=[{id:"things",number:"01",title:"Речі для щодня",text:"Носити, загортатися, дбати про себе."},{id:"gaiwan",number:"02",title:"Для чайних ритуалів",text:onePerGroup?"Чотири гайвані — від простішої до особливої. Мені достатньо однієї.":"Чотири гайвані — від простішої до особливої."},{id:"tea",number:"03",title:"Ще чашечку?",text:onePerGroup?"Три чайні подорожі. Оберіть один набір.":"Три чайні подорожі для неспішних вечорів."},{id:"music",number:"04",title:"Нехай звучить",text:"Для гітари, улюблених альбомів і гучних моментів."},{id:"games",number:"05",title:"Час пограти",text:"За столом із друзями чи у власному ігровому світі."}];
export default function Home(){
 const [reservations,setReservations]=useState<Reservation[]>([]),[ready,setReady]=useState(false),[error,setError]=useState(""),[modal,setModal]=useState<Modal|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[copied,setCopied]=useState(false);
 const trigger=useRef<HTMLElement|null>(null);
 const refresh=useCallback(async()=>{try{const response=await fetch("/api/reservations",{cache:"no-store"});const data=await response.json() as {error?:string;reservations:Reservation[]};if(!response.ok)throw new Error(data.error);setReservations(data.reservations);setReady(true);setError("");return data.reservations as Reservation[];}catch(e){setReady(false);setError(e instanceof Error?e.message:"Не вдалося оновити бронювання.");return null;}},[]);
 useEffect(()=>{void refresh();const interval=setInterval(()=>void refresh(),15000);const focus=()=>void refresh();window.addEventListener("focus",focus);const match=location.hash.match(/^#cancel=([a-z0-9-]+)\.([a-f0-9]{64})$/);if(match){const product=products.find(p=>p.id===match[1]);if(product)setModal({product,mode:"cancel",cancelToken:match[2]});history.replaceState(null,"",location.pathname);}return()=>{clearInterval(interval);window.removeEventListener("focus",focus);}},[refresh]);
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>void}}).modelContext;if(!context?.registerTool)return;const controller=new AbortController();try{context.registerTool({name:"get_wishlist",title:"Переглянути вішліст",description:"Get gifts and their shared reservation status. Does not reserve any gifts.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true},async execute(input:unknown){if(!input||typeof input!=="object"||Object.keys(input).length)throw new Error("Expected empty object");const current=await refresh();if(!current)throw new Error("Reservations unavailable");return products.map(p=>({id:p.id,name:p.name,price:p.price,url:p.url,reservation:current.find(r=>r.groupKey===groupKey(p))??null}));}},{signal:controller.signal});}catch{}return()=>controller.abort();},[refresh]);
 function open(product:Product,mode:"book"|"cancel"){trigger.current=document.activeElement as HTMLElement;setMessage("");setCopied(false);setModal({product,mode});}
 async function act(){if(!modal||busy)return;setBusy(true);setMessage("");try{const response=await fetch("/api/reservations",{method:modal.mode==="book"?"POST":"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({itemId:modal.product.id,cancelToken:modal.cancelToken})});const result=await response.json() as {error?:string;cancelToken?:string};if(!response.ok){await refresh();throw new Error(result.error);}if(modal.mode==="book")setModal({...modal,mode:"success",cancelToken:result.cancelToken});else{setModal(null);setMessage("Бронювання скасоване. Подарунок знову доступний.");}await refresh();}catch(e){setMessage(e instanceof Error?e.message:"Немає зв’язку. Перевірте підключення й оновіть список.");}finally{setBusy(false);}}
 async function copy(){if(!modal?.cancelToken)return;const link=location.origin+"/#cancel="+modal.product.id+"."+modal.cancelToken;try{await navigator.clipboard.writeText(link);setCopied(true);}catch{setMessage("Скопіюйте посилання з поля нижче.");}}
 function card(p:Product,index:number){const reservation=reservations.find(r=>r.groupKey===groupKey(p));const mine=reservation?.mine&&reservation.itemId===p.id;const alternate=reservation&&reservation.itemId!==p.id;return <article className={"gift-card"+(reservation?" is-booked":"")} key={p.id}>
 <div className="gift-image"><span className="item-index">{String(index+1).padStart(2,"0")}</span><img src={p.image} alt={p.name} loading="lazy" width="600" height="600"/><span className={"status "+(reservation?"reserved":"available")}>{!ready?"Оновлюємо…":mine?<><Check size={13}/>Ваше бронювання</>:alternate?"Інший варіант обрано":reservation?<><LockKeyhole size={12}/>Заброньовано</>:"Можна дарувати"}</span></div>
 <div className="product-meta"><span>{p.subtitle}</span><span>{price(p)}</span></div><h3>{p.name}</h3>{p.stock==="out_of_stock"&&<p className="stock-note">У магазині наразі немає в наявності</p>}
 <div className="card-actions"><a href={p.url} target="_blank" rel="noopener noreferrer">До магазину <ArrowUpRight size={17}/><span className="sr-only"> — {p.name}, нова вкладка</span></a><button disabled={!ready||!!reservation&&!mine} className={mine?"cancel-button":"book-button"} onClick={()=>open(p,mine?"cancel":"book")}>{mine?"Скасувати бронь":reservation?"Вже обрано":"Забронювати"}</button></div></article>}
 return <><a className="skip-link" href="#gifts">До подарунків</a><header className="masthead"><a className="wordmark" href="#top"><span aria-hidden="true">✳</span> МІЙ ВІШЛІСТ</a><span className="edition">ОСОБИСТА КОЛЕКЦІЯ БАЖАНЬ</span><a className="header-link" href="#how">Як це працює <ArrowUpRight size={15}/></a></header>
 <main id="top"><section className="intro"><div className="intro-copy"><p className="eyebrow">07.10 · МІЙ ДЕНЬ НАРОДЖЕННЯ</p><h1>Мій день.<br/><span>Мої бажання.</span></h1><div className="intro-bottom"><p>Цього року мені 32.<br/>Трохи музики, трохи чаю й речі, які тішать.</p><a href="#gifts" className="circle-link" aria-label="Перейти до подарунків"><ArrowDown size={24}/></a></div></div><figure className="portrait"><img src="/portrait.jpg" alt="Мій портрет на помаранчевому тлі" width="1024" height="1024" fetchPriority="high"/><figcaption><span>ПОДАРУНОК — ЦЕ УВАГА.</span><span>І я її ціную.</span></figcaption></figure></section>
 <div className="guide" id="how"><span className="guide-title"><Gift size={21}/> Маленька домовленість</span><p>Обери подарунок і забронюй — інші побачать, що він зайнятий. Якщо плани зміняться, бронювання можна скасувати.</p><span className="guide-note">Без реєстрації.<br/>Сюрприз залишається сюрпризом.</span></div>
 <nav className="contents" aria-label="Розділи вішліста"><span>У ЦЬОМУ СПИСКУ</span><div>{sections.map(s=><a key={s.id} href={"#"+s.id}>{s.id==="things"?"Речі":s.id==="gaiwan"?"Гайвані":s.id==="tea"?"Чай":s.id==="music"?"Музика":"Ігри"}<span>{products.filter(p=>p.category===s.id).length}</span></a>)}</div><span>{products.length} БАЖАНЬ</span></nav>
 <div id="gifts" className="collection">{error&&<div className="error-banner" role="alert">{error} <button onClick={()=>void refresh()}>Спробувати ще раз</button></div>}{message&&!modal&&<p className="inline-message" role="status">{message}</p>}{sections.map(s=><section className={"gift-section section-"+s.id} id={s.id} key={s.id}><div className="section-heading"><div><span className="section-number">/{s.number}</span><h2>{s.title}</h2></div><p>{s.text}</p></div><div className="gift-grid">{products.filter(p=>p.category===s.id).sort((a,b)=>s.id==="gaiwan"?(a.price??Infinity)-(b.price??Infinity):0).map(card)}</div></section>)}</div>
 <footer><div className="footer-thanks">Найкращий подарунок —<br/><em>бути поруч.</em></div><div><p>А цей список — лише кілька підказок.</p><p className="price-note">Ціни орієнтовні. Актуальну вартість, наявність<br/>та потрібний варіант перевіряй у магазині. Для Muziker<br/>ПДВ і митні платежі можуть нараховуватися окремо.</p><a href="#top">На початок ↑</a></div><span className="footer-mark" aria-hidden="true">✳</span></footer></main>
 <Dialog open={!!modal} onOpenChange={value=>{if(!value&&!busy){setModal(null);setMessage("");}}}><DialogContent className="booking-dialog" showCloseButton={false} onCloseAutoFocus={e=>{e.preventDefault();trigger.current?.focus();}}><DialogClose className="dialog-close" aria-label="Закрити" disabled={busy}><X size={22}/></DialogClose>{modal&&<><span className="eyebrow">{modal.mode==="success"?"ГОТОВО, ЦЕ ВАШ СЮРПРИЗ":modal.mode==="cancel"?"ПЛАНИ МОЖУТЬ ЗМІНЮВАТИСЯ":"ОДНА РІЧ. ОДИН ПОДАРУНОК."}</span><DialogTitle className="dialog-title">{modal.mode==="success"?"Подарунок за вами!":modal.mode==="cancel"?"Скасувати бронювання?":"Берете на себе?"}</DialogTitle><DialogDescription className="dialog-description">{modal.mode==="success"?"Інші гості вже бачать, що подарунок зайнятий. Купити його можна за посиланням у магазин.":modal.mode==="cancel"?"Подарунок знову стане доступним для інших гостей.":"Після підтвердження інші гості не зможуть забронювати цей подарунок."}</DialogDescription><div className="dialog-product"><img src={modal.product.image} alt="" width="84" height="84"/><div><strong>{modal.product.name}</strong><span>{price(modal.product)}</span></div></div>{modal.mode==="book"&&<><p className="dialog-tip">Скасувати можна в цьому браузері або за особистим посиланням, яке з’явиться після бронювання.</p>{onePerGroup&&(modal.product.category==="gaiwan"||modal.product.category==="tea")&&<p className="dialog-tip">Це один із варіантів. Бронювання також закриє решту подарунків у цій групі.</p>}<button className="primary-action" onClick={act} disabled={busy}>{busy?"Бронюємо…":"Так, я подарую"}<Check size={18}/></button></>}{modal.mode==="cancel"&&<button className="primary-action" onClick={act} disabled={busy}>{busy?"Скасовуємо…":"Так, скасувати бронювання"}</button>}{modal.mode==="success"&&<><a className="primary-action" href={modal.product.url} target="_blank" rel="noopener noreferrer">Перейти до магазину<ArrowUpRight size={18}/></a><div className="recovery"><label htmlFor="cancel-link">Особисте посилання для скасування</label><p>Збережіть його, щоб скасувати бронювання з іншого пристрою. Не діліться цим посиланням.</p><input id="cancel-link" readOnly value={typeof window!=="undefined"?location.origin+"/#cancel="+modal.product.id+"."+modal.cancelToken:""} onFocus={e=>e.target.select()}/><button onClick={copy}><Copy size={16}/>{copied?"Скопійовано":"Скопіювати посилання"}</button></div></>}{message&&<p className="dialog-error" role="alert">{message}</p>}</>}</DialogContent></Dialog></>;
}

